### ISSUE TITLE
blockpages_generator lambda sporadic failure due to "No space left on device" error

### ISSUE THREAD

**Issue by bqbn** [mozilla-services/amo2kinto-lambda#53]
We got paged from time to time due to blockpages_generator lambda failures.

Upon checking the logs, it was caused by errors similar to below

```
[Errno 28] No space left on device: '/tmp/tmp7cjkc3ey': OSError
Traceback (most recent call last):
File "/var/task/aws_lambda.py", line 288, in blockpages_generator
target_dir = mkdtemp()
File "/var/lang/lib/python3.6/tempfile.py", line 368, in mkdtemp
_os.mkdir(file, 0o700)
OSError: [Errno 28] No space left on device: '/tmp/tmp7cjkc3ey'
```

The failure is sporadic and it usually doesn't happen very often, but for the recent 4 days, it has happened twice.

Is it possible to either clean the temporary space (before or after work), or catch the exception and ignore it?

This will help reduce false alerts, besides the lambda usually correct itself after a few re-runs, so it's basically when this happens, it's not actionable by ops.

**Comment by bqbn** [comment]
Thanks for the fix, @leplatrem 

v4.3.0 lambda deployed to -stage without issues.

I'm currently waiting for https://bugzilla.mozilla.org/show_bug.cgi?id=1495493 before deploying v4.3.0 to -prod (since no urgency for us to get this out).
